INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(1, 'Agriculture');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(2, 'Architecture');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(3, 'Area Studies');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(4, 'Biological Sciences');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(5, 'Business and Management');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(6, 'Communications');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(7, 'Computer and Info. Sciences');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(8, 'Education');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(9, 'Engineering');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(10, 'Fine and Applied Arts');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(11, 'Foreign Languages');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(12, 'Health Professions');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(13, 'Home Economics');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(14, 'Interdisciplinary Studies');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(15, 'Letters');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(16, 'Library');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(17, 'Mathematics');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(18, 'Physical Sciences');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(19, 'Psychology');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(20, 'Public Affairs');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(21, 'Social Sciences');
INSERT INTO disciplinesList(disciplineID, disciplineName) VALUES(22, 'Undeclared');
