INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Aberdeen ', 'APG', 'Phillips AAF ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Aberdeen ', 'ABR', 'Municipal ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Abilene ', 'DYS', 'Dyess AFB ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Abilene ', 'ABI', 'Municipal ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Abingdon ', 'VJI', 'Virginia Highlands ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Ada ', 'ADT', 'Ada ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Adak Island ', 'ADK', 'Adak Island Ns ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Adrian ', 'ADG', 'Lenawee County ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Afton ', 'AFO', 'Municipal ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Aiken ', 'AIK', 'Municipal ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Ainsworth ', 'ANW', 'Ainsworth ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Akhiok ', 'AKK', 'Akhiok SPB ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Akiachak ', 'KKI', 'Spb ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Akiak ', 'AKI', 'Akiak ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Akron CO ' , 'AKO', 'Colorado Plains Regional Airport ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Akron/Canton OH ' , 'CAK', 'Akron/canton Regional ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Akron/Canton ', 'AKC', 'Fulton International ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Akutan ', 'KQA', 'Akutan ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Alakanuk ', 'AUK', 'Alakanuk ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Alameda ', 'NGZ', 'NAS ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Alamogordo ', 'HMN', 'Holloman AFB ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Alamogordo ', 'ALM', 'Municipal ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Alamosa ', 'ALS', 'Municipal ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Albany ', 'NAB', 'Albany NAS ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Albany ', 'ABY', 'Dougherty County ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Albany ', 'ALB', 'Albany International ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Albany ', 'CVO', 'Albany ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Albert Lea ', 'AEL', 'Albert Lea ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Albuquerque ', 'ABQ', 'Albuquerque International ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Aleknagik ', 'WKK', 'Aleknagik ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Aleneva ', 'AED', 'Aleneva ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES( 'Alexander City AL ' , 'ALX', 'Thomas C Russell Fld ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES( 'Alexandria LA ' , 'AEX', 'Alexandria International ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Alexandria ', 'ESF', 'Esler Field ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Alexandria ', 'AXN', 'Alexandria ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Alexandria Bay ', 'AXB', 'Alexandria Bay ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Algona ', 'AXG', 'Algona ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Alice ', 'ALI', 'International ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES( 'Aliceville AL ' , 'AIV', 'George Downer ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Alitak ', 'ALZ', 'Alitak SPB ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Allakaket ', 'AET', 'Allakaket ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Alliance ', 'AIA', 'Alliance ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Alma ', 'AMN', 'Gratiot Community ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Alpena ', 'APN', 'Alpena County Regional ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Alpine ', 'ALE', 'Alpine ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Alton ', 'ALN', 'Alton ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Altus ', 'LTS', 'Altus AFB ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Altus ', 'AXS', 'Municipal ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Alyeska ', 'AQY', 'Alyeska ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES( 'Amarillo  ' , 'AMA', 'Rick Husband Amarillo International ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Amarillo ', 'TDW', 'Tradewind ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Ambler ', 'ABL', 'Ambler ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Amchitka ', 'AHT', 'Amchitka ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Amery ', 'AHH', 'Municipal ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Ames ', 'AMW', 'Ames ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Amityville ', 'AYZ', 'Zahns ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Amook ', 'AOS', 'Amook ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Anacortes ', 'OTS', 'Anacortes ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Anacostia ', 'NDV', 'USN Heliport ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Anaheim ', 'ANA', 'Orange County Steel Salvage Heliport ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Anaktuvuk ', 'AKP', 'Anaktuvuk ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Anchorage ', 'EDF', 'Elmendorf Afb ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Anchorage ', 'ANC', 'Ted Stevens Anchorage International Airport ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Anchorage ', 'MRI', 'Merrill Field ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Anderson ', 'AID', 'Municipal ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Anderson ', 'AND', 'Anderson ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Andrews ', 'ADR', 'Andrews ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Angel Fire ', 'AXX', 'Angel Fire ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Angola ', 'ANQ', 'Tri-State Steuben Cty ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Angoon ', 'AGN', 'Angoon ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Anguilla ', 'RFK', 'Rollang Field ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Aniak ', 'ANI', 'Aniak ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Anita Bay ', 'AIB', 'Anita Bay ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES( 'Ann Arbor MI ' , 'ARB', 'Municipal ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Annapolis ', 'ANP', 'Lee ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Annette Island ', 'ANN', 'Annette Island ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES( 'Anniston AL ' , 'ANB', 'Anniston Metropolitan ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Anniston ', 'QAW', 'Ft Mcclellan Bus Trml ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Anniston ', 'RLI', 'Reilly AHP ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Anthony ', 'ANY', 'Anthony ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Antlers ', 'ATE', 'Antlers ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Anvik ', 'ANV', 'Anvik ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Apalachicola ', 'AAF', 'Municipal ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Apple Valley ', 'APV', 'Apple Valley ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Appleton ', 'ATW', 'Outagamie County ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Arapahoe ', 'AHF', 'Municipal ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Arcata ', 'ACV', 'Arcata ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Arctic Village ', 'ARC', 'Arctic Village ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Ardmore ', 'AHD', 'Downtown ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Ardmore ', 'ADM', 'Ardmore Municipal Arpt ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Arlington Heights ', 'JLH', 'US Army Heliport ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Artesia ', 'ATS', 'Artesia ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES( 'Neptune ' , 'ARX', 'Asbury Park ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Ashland ', 'ASX', 'Ashland ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Ashley ', 'ASY', 'Ashley ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Aspen ', 'ASE', 'Aspen ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Astoria ', 'AST', 'Astoria ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Athens ', 'AHN', 'Athens ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Athens ', 'ATO', 'Ohio University ', 'United States ', 'US ');
INSERT INTO airportsList(airportCity, airportCode, airportName, airportCountry, countryAbbreviation) VALUES('Athens ', 'MMI', 'McMinn County ', 'United States ', 'US ');
