INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(1, 'amc', 'American Motor Company');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(2, 'volkswagen', 'Volkswagen');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(3, 'bmw', 'BMW');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(4, 'gm', 'General Motors');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(5, 'ford', 'Ford Motor Company');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(6, 'chrysler', 'Chrysler');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(7, 'citroen', 'Citroen');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(8, 'nissan', 'Nissan Motors');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(9, 'fiat', 'Fiat');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(10, 'hi', 'hi');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(11, 'honda', 'Honda');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(12, 'mazda', 'Mazda');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(13, 'daimler benz', 'Daimler Benz');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(14, 'opel', 'Opel');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(15, 'peugeaut', 'Peugeaut');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(16, 'renault', 'Renault');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(17, 'saab', 'Saab');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(18, 'subaru', 'Subaru');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(19, 'toyota', 'Toyota');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(20, 'triumph', 'Triumph');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(21, 'volvo', 'Volvo');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(22, 'kia', 'Kia Motors');
INSERT INTO carMakersList(carMakerID, carMakerShort, carMakerName) VALUES(23, 'hyundai', 'Hyundai');
