INSERT INTO songsList(songID, songTitle) VALUES(1, 'Overture');
INSERT INTO songsList(songID, songTitle) VALUES(2, 'A Bar In Amsterdam');
INSERT INTO songsList(songID, songTitle) VALUES(3, 'Demon Kitty Rag');
INSERT INTO songsList(songID, songTitle) VALUES(4, 'Tea With Cinnamon');
INSERT INTO songsList(songID, songTitle) VALUES(5, 'Hey Ho on the Devil''s Back');
INSERT INTO songsList(songID, songTitle) VALUES(6, 'Wading in Deeper');
INSERT INTO songsList(songID, songTitle) VALUES(7, 'Le Pop');
INSERT INTO songsList(songID, songTitle) VALUES(8, 'Der Kapitan');
INSERT INTO songsList(songID, songTitle) VALUES(9, 'Virginia Clemm');
INSERT INTO songsList(songID, songTitle) VALUES(10, 'Play My Darling,  Play');
INSERT INTO songsList(songID, songTitle) VALUES(11, 'To the Sea');
INSERT INTO songsList(songID, songTitle) VALUES(12, 'Mother Superior');
INSERT INTO songsList(songID, songTitle) VALUES(13, 'Ain\'t no Thang');
INSERT INTO songsList(songID, songTitle) VALUES(14, 'A Kiss Before You Go');
INSERT INTO songsList(songID, songTitle) VALUES(15, 'I Will Dance (When I Walk Away)');
INSERT INTO songsList(songID, songTitle) VALUES(16, 'Cherry Pie');
INSERT INTO songsList(songID, songTitle) VALUES(17, 'Land of Confusion');
INSERT INTO songsList(songID, songTitle) VALUES(18, 'Lady Marlene');
INSERT INTO songsList(songID, songTitle) VALUES(19, 'Rock-Paper-Scissors');
INSERT INTO songsList(songID, songTitle) VALUES(20, 'Cocktails and Ruby Slippers');
INSERT INTO songsList(songID, songTitle) VALUES(21, 'Soviet Trumpeter');
INSERT INTO songsList(songID, songTitle) VALUES(22, 'Loathsome M');
INSERT INTO songsList(songID, songTitle) VALUES(23, 'Shepherd\'s Song');
INSERT INTO songsList(songID, songTitle) VALUES(24, 'Gypsy Flee');
INSERT INTO songsList(songID, songTitle) VALUES(25, 'God\'s Great Dust Storm');
INSERT INTO songsList(songID, songTitle) VALUES(26, 'Ouch');
INSERT INTO songsList(songID, songTitle) VALUES(27, 'Listening to the World');
INSERT INTO songsList(songID, songTitle) VALUES(28, 'Johnny Blowtorch');
INSERT INTO songsList(songID, songTitle) VALUES(29, 'Flash');
INSERT INTO songsList(songID, songTitle) VALUES(30, 'Driving After You');
INSERT INTO songsList(songID, songTitle) VALUES(31, 'My Own Tune');
INSERT INTO songsList(songID, songTitle) VALUES(32, 'Badlands');
INSERT INTO songsList(songID, songTitle) VALUES(33, 'Old De Spain');
INSERT INTO songsList(songID, songTitle) VALUES(34, 'Oh My God');
INSERT INTO songsList(songID, songTitle) VALUES(35, 'Lady Gray');
INSERT INTO songsList(songID, songTitle) VALUES(36, 'Shine Like Neon Rays');
INSERT INTO songsList(songID, songTitle) VALUES(37, 'Flash in the Dark');
INSERT INTO songsList(songID, songTitle) VALUES(38, 'My Dear');
INSERT INTO songsList(songID, songTitle) VALUES(39, 'Bad Girl');
INSERT INTO songsList(songID, songTitle) VALUES(40, 'Rockland');
INSERT INTO songsList(songID, songTitle) VALUES(41, 'Curvaceous Needs');
INSERT INTO songsList(songID, songTitle) VALUES(42, 'Borka');
INSERT INTO songsList(songID, songTitle) VALUES(43, 'Let it Snow');
