INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(1, 'Barbera', 'Red');
INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(2, 'Cabernet Franc', 'Red');
INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(3, 'Cabernet Sauvingnon', 'Red');
INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(4, 'Chardonnay', 'White');
INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(5, 'Grenache', 'Red');
INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(6, 'Malbec', 'Red');
INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(7, 'Marsanne', 'White');
INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(8, 'Merlot', 'Red');
INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(9, 'Mourvedre', 'Red');
INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(10, 'Muscat', 'White');
INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(11, 'Petite Sirah', 'Red');
INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(12, 'Pinot Noir', 'Red');
INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(13, 'Riesling', 'White');
INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(14, 'Roussanne', 'White');
INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(15, 'Sangiovese', 'Red');
INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(16, 'Sauvignon Blanc', 'White');
INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(17, 'Syrah', 'Red');
INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(18, 'Tempranillo', 'Red');
INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(19, 'Viognier', 'White');
INSERT INTO grapesList(grapeID, grapeName, grapeColor) VALUES(20, 'Zinfandel', 'Red');
